### ISSUE TITLE
image-upload.js 404

### ISSUE THREAD

**Issue by olpo24** [qualmy91/toolbox-for-asgaros-forum#4]
Hi,
in the chome console I'm getting a 404 for the image-upload.js.

![image](https://user-images.githubusercontent.com/48469242/90341972-96a35900-e004-11ea-93b5-2c51c68dcdef.png)

Kind regards,
Ole

**Comment by olpo24** [comment]
image-upload.js seems to be missing in the plugin version 1.1.3. in the wp repository

**Comment by qualmy91** [comment]
Hey Ole, 

thanks for the info. I fixed it right now with the update 1.1.4 

Best regards, 
Domi
